import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createRequire } from 'node:module';
import { createServer } from './serve.mjs';
import { getBrowser } from './browser.mjs';
const root = fileURLToPath(new URL('..', import.meta.url));
const require = createRequire(import.meta.url);
const axePath = require.resolve('axe-core/axe.min.js');
const artifacts = path.join(root, 'artifacts');
await mkdir(artifacts, { recursive: true });
const server = await createServer(0);
const base = `http://127.0.0.1:${server.address().port}`;
let browser;
try {
  browser = await getBrowser();
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = [];
  const missing = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.url().startsWith(base) && r.status() >= 400) missing.push(r.url()); });
  const submissions = [];
  page.on('request', request => { if (request.method() === 'POST') submissions.push(request.url()); });
  await page.route('https://**/*', route => route.abort());
  await page.goto(base, { waitUntil: 'networkidle' });
  const choose = async (name, text) => {
    await page.locator(`[data-select="${name}"]`).click();
    await page.getByRole('option', { name: text, exact: false }).click();
  };
  await page.evaluate(() => document.fonts.ready);
  async function checkAccessibility() {
    await page.addScriptTag({path: axePath});
    const violations = await page.evaluate(async () => (await axe.run(document, {
      runOnly: {type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa']},
    })).violations.map(({id,nodes})=>({id,targets:nodes.map(node=>node.target)})));
    assert.deepEqual(violations, [], 'Accessibility violations');
  }
  assert.equal(await page.title(), 'DreamPC — Twój sprzęt. Nowy poziom. | Białystok');
  for (const width of [320, 360, 390, 540, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    const sizes = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }));
    assert.ok(sizes.scroll <= sizes.viewport + 1, `Horizontal overflow at ${width}: ${JSON.stringify(sizes)}`);
    await checkAccessibility();
  }
  async function loadImages() {
    await page.evaluate(async () => {
      document.querySelectorAll('img[loading="lazy"]').forEach(img => { img.loading = 'eager'; });
      await Promise.all([...document.images].map(img => img.decode()));
    });
  }
  await loadImages();
  await page.screenshot({ path: path.join(artifacts, 'desktop.png'), fullPage: true });
  await page.locator('[data-filter="repair"]').click();
  assert.equal(await page.locator('.service-card:visible').count(), 3);
  await page.locator('[data-filter="all"]').click();
  assert.equal(await page.locator('.service-card:visible').count(), 6);
  await page.locator('[data-usage="creative"]').click();
  await page.locator('[data-style="Biały"]').click();
  await page.locator('#budget').fill('8500');
  await page.locator('#peripherals').check();
  assert.match(await page.locator('#summaryBudget').innerText(), /8\s*500/);
  await page.locator('#buildRequest').click();
  assert.equal(await page.locator('#serviceSelect').inputValue(), 'build');
  assert.match(await page.locator('[data-select="service"]').innerText(), /Budowa nowego PC/);
  await page.locator('[data-select="service"]').click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#bookingDialog').isVisible(), true, 'Escape closes dropdown before dialog');
  assert.equal(await page.locator('[data-select="service"]').getAttribute('aria-expanded'), 'false');
  assert.match(await page.locator('#buildBrief').innerText(), /Biały/);
  await page.locator('#nextStep').click();
  assert.equal(await page.locator('[data-step="0"]').isVisible(), true, 'Missing description must block next step');
  assert.equal(await page.locator('[name="problem"]').getAttribute('aria-invalid'), 'true');
  await checkAccessibility();
  await page.locator('[name="problem"]').fill('Montaż filmów i Blender. Mam już klawiaturę.');
  await page.locator('#nextStep').click();
  await page.locator('[name="name"]').fill('Test DreamPC');
  await page.locator('[name="phone"]').fill('abc');
  await page.locator('#nextStep').click();
  assert.equal(await page.locator('[data-step="1"]').isVisible(), true, 'Invalid phone must block next step');
  await page.locator('[name="phone"]').fill('500 000 000');
  await choose('contact', 'E-mail');
  await page.locator('#nextStep').click();
  assert.equal(await page.locator('[data-step="1"]').isVisible(), true, 'Email preference requires email');
  await page.locator('[name="email"]').fill('test@example.com');
  await page.locator('#nextStep').click();
  assert.match(await page.locator('#requestSummary').innerText(), /8\s*500/);
  assert.match(await page.locator('#estimateNote').innerText(), /Transport do uzgodnienia/);
  await page.locator('#sendRequest').click();
  assert.equal(await page.locator('#successPanel').isVisible(), false, 'Acknowledgement required');
  assert.deepEqual(submissions, []);
  await page.locator('[name="acknowledgement"]').check();
  await page.locator('#sendRequest').dblclick();
  await page.locator('#successPanel').waitFor({ state: 'visible' });
  assert.match(await page.locator('#successPanel').innerText(), /Nic nie zostało wysłane/);
  assert.deepEqual(submissions, [], 'Demo must not send data');
  const firstTicket = await page.locator('#successTicket').innerText();
  assert.match(firstTicket, /^DEMO-\d{8}-[0-9A-F]{12}$/);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#downloadRequest').click();
  const download = await downloadPromise;
  const downloaded = await readFile(await download.path(), 'utf8');
  assert.match(downloaded, /Blender/);
  assert.ok(downloaded.includes(firstTicket));
  assert.match(downloaded, /dane nie zostały wysłane/);
  assert.match(downloaded, /Biały/);
  assert.match(downloaded, /8\s*500/);
  await page.keyboard.press('Escape');
  await page.locator('.nav-cta').click();
  await page.locator('[data-select="device"]').focus();
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('[name="device"]').inputValue(), 'Laptop', 'Keyboard selection updates native value');
  await page.locator('[name="problem"]').fill('<img src=x onerror=alert(1)> laptop');
  await page.locator('#nextStep').click();
  await page.locator('[name="name"]').fill('Drugi test');
  await page.locator('[name="phone"]').fill('+48 500 000 000');
  await page.locator('#nextStep').click();
  assert.equal(await page.locator('#requestSummary img').count(), 0, 'User input must render as text');
  await page.locator('[name="acknowledgement"]').check();
  await page.locator('#sendRequest').click();
  await page.locator('#successPanel').waitFor({ state: 'visible' });
  assert.notEqual(await page.locator('#successTicket').innerText(), firstTicket, 'New enquiries need new IDs');
  await checkAccessibility();
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base, { waitUntil: 'networkidle' });
  await loadImages();
  await page.screenshot({ path: path.join(artifacts, 'mobile.png'), fullPage: true });
  await page.locator('.menu-toggle').click();
  assert.equal(await page.locator('#navigation').isVisible(), true);
  await page.locator('#navigation a[href="#faq"]').click();
  assert.equal(await page.locator('#navigation').isVisible(), false);
  await page.locator('.mobile-dock [data-book]').click();
  await page.locator('[data-select="service"]').click();
  await checkAccessibility();
  await page.screenshot({ path: path.join(artifacts, 'mobile-select.png') });
  await page.getByRole('option', { name: /Czyszczenie i pasta/ }).click();
  assert.equal(await page.locator('#serviceSelect').inputValue(), 'cleaning');
  await page.locator('#nextStep').click();
  assert.equal(await page.locator('[data-select="device"]').getAttribute('aria-invalid'), 'true');
  await choose('device', 'Laptop');
  assert.equal(await page.locator('[data-select="device"]').getAttribute('aria-invalid'), null);
  await page.screenshot({ path: path.join(artifacts, 'mobile-form.png') });
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(() => document.body.classList.contains('modal-open')), false);
  await page.locator('[data-preset="work"]').click();
  assert.equal(await page.locator('[data-usage="work"]').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('#buildCategory').innerText(), 'PRACA I NAUKA');
  await page.goto(base + '/privacy.html');
  await checkAccessibility();
  await page.goto(base + '/tools/materials.html', { waitUntil: 'networkidle' });
  await page.screenshot({ path: path.join(artifacts, 'brand-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => [...document.images].every(img => img.complete && img.naturalWidth > 0)), true);
  assert.deepEqual(submissions, [], 'No form data leaves the browser');
  assert.deepEqual(errors, []);
  assert.deepEqual(missing, []);
  console.log('PASS: 7 viewport widths; WCAG AA; filters; builder and presets; field validation; unique demo IDs; local receipt; XSS; mobile menu and assets. No form submissions.');
} finally {
  if (browser) await browser.close();
  await new Promise(resolve => server.close(resolve));
}
